db:
  database: 'event_maker_development'
  user: 'postgres'
  password: '123456'
  host: 'localhost'
  port: '5432'
app:
  max_files_at_time: 100
  target_dirs:
    events: 'EVENTS'
  source_dirs:
    logs: 'LOGS'